TeapotioBaseForumBundle_listMessages:
    pattern:  /list-messages/{topicId}/
    defaults: { _controller: TeapotioBaseForumBundle:Module:listMessages }

TeapotioBaseForumBundle_listTopics:
    pattern:  /list-topics/
    defaults: { _controller: TeapotioBaseForumBundle:Module:listTopics }

TeapotioBaseForumBundle_listTopicsInBoard:
    pattern:  /list-topics/{boardId}/
    defaults: { _controller: TeapotioBaseForumBundle:Module:listTopics }

TeapotioBaseForumBundle_listBoards:
    pattern:  /list-boards/
    defaults: { _controller: TeapotioBaseForumBundle:Module:listBoards }

TeapotioBaseForumBundle_newMessage:
    pattern:  /new-message/{topicId}/
    defaults: { _controller: TeapotioBaseForumBundle:Module:newMessage }

TeapotioBaseForumBundle_newTopic:
    pattern:  /new-topic/{boardId}/
    defaults: { _controller: TeapotioBaseForumBundle:Module:newTopic }

TeapotioBaseForumBundle_newBoard:
    pattern:  /new-board/
    defaults: { _controller: TeapotioBaseForumBundle:Module:newBoard }
