parameters:
    teapotio.forum.url.use_id: false

    teapotio_forum.access_permission_service.class:   Teapotio\Base\ForumBundle\Service\AccessPermissionService
    teapotio_forum.board_service.class:               Teapotio\Base\ForumBundle\Service\BoardService
    teapotio_forum.flag_service.class:                Teapotio\Base\ForumBundle\Service\FlagService
    teapotio_forum.topic_service.class:               Teapotio\Base\ForumBundle\Service\TopicService
    teapotio_forum.message_service.class:             Teapotio\Base\ForumBundle\Service\MessageService
    teapotio_forum.message_star_service.class:        Teapotio\Base\ForumBundle\Service\MessageStarService
    teapotio_forum.moderation_service.class:          Teapotio\Base\ForumBundle\Service\ModerationService
    teapotio_forum.main_service.class:                Teapotio\Base\ForumBundle\Service\MainService
    teapotio_forum.flag_service.class:                Teapotio\Base\ForumBundle\Service\PathService
    teapotio_forum.path_service.class:                Teapotio\Base\ForumBundle\Service\UserStatService
    teapotio_forum.access_permission_extension.class: Teapotio\Base\ForumBundle\Extension\AccessPermission
    teapotio_forum.data_access_extension.class:       Teapotio\Base\ForumBundle\Extension\DataAccess
    teapotio_forum.date_extension.class:              Teapotio\Base\ForumBundle\Extension\Date
    teapotio_forum.path_extension.class:              Teapotio\Base\ForumBundle\Extension\Path

    teapotio_forum.board_repository.class:        'TeapotioBaseForumBundle:Board'
    teapotio_forum.flag_repository.class:         'TeapotioBaseForumBundle:Flag'
    teapotio_forum.topic_repository.class:        'TeapotioBaseForumBundle:Topic'
    teapotio_forum.message_repository.class:      'TeapotioBaseForumBundle:Message'
    teapotio_forum.message_star_repository.class: 'TeapotioBaseForumBundle:MessageStar'
    teapotio_forum.moderation_repository.class:   'TeapotioBaseForumBundle:Moderation'
    teapotio_forum.user_stat_repository.class:    'TeapotioBaseForumBundle:UserStat'

services:
    teapotio.forum.access_permission:
        class: %teapotio_forum.access_permission_service.class%
        arguments: [@service_container]
    teapotio.forum.board:
        class: %teapotio_forum.board_service.class%
        arguments: [@service_container]
    teapotio.forum.flag:
        class: %teapotio_forum.flag_service.class%
        arguments: [@service_container]
    teapotio.forum.topic:
        class: %teapotio_forum.topic_service.class%
        arguments: [@service_container]
    teapotio.forum.message:
        class: %teapotio_forum.message_service.class%
        arguments: [@service_container]
    teapotio.forum.message_star:
        class: %teapotio_forum.message_star_service.class%
        arguments: [@service_container]
    teapotio.forum.moderation:
        class: %teapotio_forum.moderation_service.class%
        arguments: [@service_container]
    teapotio.forum.path:
        class: %teapotio_forum.path_service.class%
        arguments: [@service_container]
    teapotio.forum.user_stat:
        class: %teapotio_forum.user_stat_service.class%
        arguments: [@service_container]
    teapotio.forum:
        class: %teapotio_forum.main_service.class%
        arguments: [@service_container]
    teapotio.extension.access_permission:
        class: %teapotio_forum.access_permission_extension.class%
        tags: [{ name: twig.extension }]
        arguments: [@service_container]
    teapotio.extension.data_access:
        class: %teapotio_forum.data_access_extension.class%
        tags: [{ name: twig.extension }]
        arguments: [@service_container]
    teapotio.extension.date:
        class: %teapotio_forum.date_extension.class%
        tags: [{ name: twig.extension }]
        arguments: [@service_container]
    teapotio.extension.path:
        class: %teapotio_forum.path_extension.class%
        tags: [{ name: twig.extension }]
        arguments: [@service_container]
